"""Versioned project persistence for NeoEng-D-Trace."""

from .errors import (
    LegacyProjectMigrationError,
    ProjectFormatError,
    ProjectPersistenceError,
    ProjectReadError,
    ProjectValidationError,
    ProjectWriteError,
    UnsupportedProjectVersionError,
)
from .project_io import (
    LoadedProject,
    apply_project_document_to_scene,
    build_project_document,
    load_project_document,
    load_project_into_scene,
    save_scene_project,
)
from .project_schema import (
    MAX_PROJECT_FILE_BYTES,
    MAX_PROJECT_OBJECTS,
    MAX_PROJECT_POINTS,
    PROJECT_FILE_EXTENSION,
    ProjectDocumentV1,
)
from .scenario_io import (
    ScenarioFormatError,
    ScenarioReadError,
    ScenarioValidationError,
    ScenarioWriteError,
    hash_project_file,
    load_scenario,
    project_reference_for,
    save_scenario,
    scenario_sha256,
    serialize_scenario,
    verify_project_reference,
)
from .scenario_schema import (
    SCENARIO_FILE_EXTENSION,
    SCENARIO_FORMAT_ID,
    SCENARIO_SCHEMA_VERSION,
    ScenarioDocumentV1,
)

__all__ = [
    "LegacyProjectMigrationError",
    "LoadedProject",
    "MAX_PROJECT_FILE_BYTES",
    "MAX_PROJECT_OBJECTS",
    "MAX_PROJECT_POINTS",
    "PROJECT_FILE_EXTENSION",
    "ProjectDocumentV1",
    "ProjectFormatError",
    "ProjectPersistenceError",
    "ProjectReadError",
    "ProjectValidationError",
    "ProjectWriteError",
    "UnsupportedProjectVersionError",
    "SCENARIO_FILE_EXTENSION",
    "SCENARIO_FORMAT_ID",
    "SCENARIO_SCHEMA_VERSION",
    "ScenarioDocumentV1",
    "ScenarioFormatError",
    "ScenarioReadError",
    "ScenarioValidationError",
    "ScenarioWriteError",
    "hash_project_file",
    "load_scenario",
    "project_reference_for",
    "save_scenario",
    "scenario_sha256",
    "serialize_scenario",
    "verify_project_reference",
    "apply_project_document_to_scene",
    "build_project_document",
    "load_project_document",
    "load_project_into_scene",
    "save_scene_project",
]
