"""Generate the chained, reviewable Stage 4 evidence snapshot."""
from __future__ import annotations
import argparse,hashlib,json,platform,subprocess,sys,xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

def sha256(path:Path)->str:return hashlib.sha256(path.read_bytes()).hexdigest()
def git(*args:str)->str:return subprocess.run(["git",*args],check=True,capture_output=True,text=True,encoding="utf-8").stdout.strip()
def write_json(path:Path,payload:dict[str,Any])->None:path.write_text(json.dumps(payload,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
def inventory(root:Path,commit:str)->dict[str,Any]:
    paths=[Path("src/ui/reference_chrome.py"),Path("src/ui/responsive_layout.py"),Path("src/ui/tool_palette_impl.py"),Path("src/ui/main_window_translations.py"),Path("tests/test_stage4_ui_top_toolbar.py"),Path("tests/test_stage3_ui_toolbar.py"),Path("scripts/audit_stage4_contract.py"),Path("scripts/generate_stage4_snapshot.py"),Path("scripts/record_stage4_approval.py"),Path("docs/evidence/STAGE4_SCOPE_AND_RECONCILIATION.md")]
    return {"schema":"neoeng.stage4-inventory","schema_version":1,"source_commit":commit,"files":[{"path":p.as_posix(),"sha256":sha256(root/p)} for p in paths]}
def main()->int:
    parser=argparse.ArgumentParser(); parser.add_argument("--output",type=Path,required=True); parser.add_argument("--parent",type=Path,required=True); parser.add_argument("--audit",type=Path,required=True); parser.add_argument("--full-suite",type=Path,required=True); parser.add_argument("--final-target",type=Path,default=Path("docs/evidence/final-target-baseline-v1.json")); args=parser.parse_args(); root=Path.cwd().resolve(); output=args.output.resolve(); output.mkdir(parents=True,exist_ok=True); audit=json.loads(args.audit.resolve().read_text(encoding="utf-8")); parent=json.loads(args.parent.resolve().read_text(encoding="utf-8")); commit=git("rev-parse","HEAD")
    if audit.get("status")!="PASS" or audit.get("source_state",{}).get("commit")!=commit: raise SystemExit("Stage 4 audit is not PASS on current HEAD")
    if not str(parent.get("snapshot_id","")).startswith("STAGE_3_SNAPSHOT:"): raise SystemExit("parent is not a Stage 3 snapshot")
    inventory_path=output/"stage4-inventory.json"; write_json(inventory_path,inventory(root,commit)); suite_root=ET.parse(args.full_suite.resolve()).getroot(); suite_node=suite_root.find("testsuite") if suite_root.tag=="testsuites" else suite_root
    if suite_node is None: raise SystemExit("JUnit has no testsuite")
    suite={"tests":int(suite_node.attrib.get("tests",0)),"failures":int(suite_node.attrib.get("failures",0)),"errors":int(suite_node.attrib.get("errors",0)),"skipped":int(suite_node.attrib.get("skipped",0)),"time_seconds":float(suite_node.attrib.get("time",0.0)),"status":"PASS" if all(int(suite_node.attrib.get(k,0))==0 for k in ("failures","errors")) else "FAIL","junit":{"path":args.full_suite.resolve().relative_to(output).as_posix(),"sha256":sha256(args.full_suite.resolve())}}
    audit_checks=audit.get("checks",{}); live=audit_checks.get("live_contract",{}); checks=[{"id":"stage4.live_contract","classification":"EXPECTED_EVOLUTION","justification":"The current visible toolbar, canonical duplicate-action mapping, menus and three-resolution geometry were exercised through the real MainWindow.","result":live.get("status","FAIL")},{"id":"stage4.visual_capture","classification":"EXPECTED_EVOLUTION","justification":"Real Qt captures were processed by the existing Pillow/OpenCV/Qt visual auditor.","result":audit_checks.get("visual_status","FAIL")},{"id":"stage4.capture_pipeline","classification":"EXPECTED_EVOLUTION","justification":"The reproducible capture pipeline completed and generated the raw manifest.","result":audit_checks.get("capture_status","FAIL")},{"id":"stage4.full_suite","classification":"EXPECTED_EVOLUTION","justification":"The complete repository suite is hash-referenced through its JUnit output.","result":suite["status"]}]
    excluded={"stage4-report.json","stage4-manifest.json","stage4-inventory.json"}; artifacts=[{"path":p.relative_to(output).as_posix(),"sha256":sha256(p),"purpose":"Etapa 4 technical evidence.","visual":p.suffix.lower()==".png"} for p in sorted(output.rglob("*")) if p.is_file() and p.name not in excluded]
    report={"schema":"neoeng.stage-audit-report","schema_version":1,"stage":4,"stage_name":"Barra superior agrupada","baseline_id":"FINAL_TARGET","parent_snapshot_id":parent["snapshot_id"],"commit":commit,"command":"python scripts/generate_stage4_snapshot.py --output artifacts/stage4-snapshot-20260824 --parent artifacts/stage3-snapshot-20260824/stage3-manifest.json --audit artifacts/stage4-snapshot-20260824/stage4-contract-audit.json --full-suite artifacts/stage4-snapshot-20260824/full-suite-junit.xml","ci_exact_commit":None,"environment":{"platform":platform.platform(),"python":sys.version,"dpi_percent":[100,125,150,200],"resolutions":["1280x720","1366x768","1920x1080"]},"audit":{"path":"stage4-contract-audit.json","sha256":sha256(output/"stage4-contract-audit.json")},"full_suite":suite,"checks":checks,"artifacts":artifacts,"decision":"REVIEW_REQUIRED","current_contract_result":"PASS","human_review":None,"limitations":audit.get("limitations",[])}
    report_path=output/"stage4-report.json"; write_json(report_path,report)
    manifest={"schema":"neoeng.stage4-snapshot","schema_version":1,"snapshot_id":f"STAGE_4_SNAPSHOT:{commit}","parent_snapshot_id":parent["snapshot_id"],"parent_manifest_sha256":sha256(args.parent.resolve()),"final_target_manifest_sha256":sha256((root/args.final_target).resolve()),"stage4_report":{"path":"stage4-report.json","sha256":sha256(report_path)},"report":{"path":"stage4-report.json","sha256":sha256(report_path)},"inventory":{"path":"stage4-inventory.json","sha256":sha256(inventory_path)},"artifacts":artifacts}; write_json(output/"stage4-manifest.json",manifest); print(json.dumps({"snapshot_id":manifest["snapshot_id"],"decision":report["decision"],"artifacts":len(artifacts)},sort_keys=True)); return 0
if __name__=="__main__": raise SystemExit(main())
